POST https://node-video-1xu0.onrender.com/videos
Content-Type: application/json

{
  "title": "Video node",
  "description": "Esse é o primeiro video",
  "duration": 180
}

###
GET https://node-video-1xu0.onrender.com/videos
###
PUT https://node-video-1xu0.onrender.com/videos/ffcfb837-a71a-434e-b237-f4386955283d
Content-Type: application/json

{
  "title": "Video 02",
  "description": "Esse é o primeiro video",
  "duration": 180
}

###
DELETE  https://node-video-1xu0.onrender.com/videos/ffcfb837-a71a-434e-b237-f4386955283d
Content-Type: application/json

{
  "title": "Video 02",
  "description": "Esse é o primeiro video",
  "duration": 180
}